---

- name: Add module
  apache2_module:
    state: present
    name: "{{item}}"
  with_items:
    - rewrite
    - ssl
  notify: restart apache phpldapadmin

- name: Copy apache config
  template:
    dest: "/etc/apache2/sites-available/{{ inventory_hostname }}.conf"
    src: apache.conf.j2
    owner: root
    group: root
    mode: "0644"
  notify: restart apache phpldapadmin

- name: Remove default apache2 site.
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent
  notify: restart apache phpldapadmin

- name: Activate apache site.
  file:
    path: "/etc/apache2/sites-enabled/{{ inventory_hostname }}.conf"
    src: "/etc/apache2/sites-available/{{ inventory_hostname }}.conf"
    state: link
  notify: restart apache phpldapadmin
